name: Node CI (server)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: server/package.json

      - name: Install
        run: npm ci

      - name: Type-check & build
        run: |
          npx tsc --version
          npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-dist
          path: server/dist
